# Generated by Django 4.2.5 on 2025-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friendOf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='AccountID',
            field=models.CharField(max_length=20),
        ),
    ]
