# Generated by Django 4.2.5 on 2025-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_alter_friends_friendof_alter_transactions_accountid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1000)),
                ('timeOfSubmission', models.DateTimeField()),
            ],
        ),
    ]
